### ISSUE TITLE
Downloads Error

### ISSUE THREAD

**Issue by CashOver** [OvO7000/DeviantArtDownloader#2]
hi, I would like to let you know that the program is not working, it is giving downloads error, I would also like to know if I can better the program

**Comment by OvO7000** [comment]
Can you describle your procedure when you download , or give some information about the download error? Like the artist and folder you were downloading.

**Comment by CashOver** [comment]
Yes, it is giving a download error when the album is 300 and above 1000, because it is lost around 10% to 50% of the image, and also a connection error to the computer when installing, sorry for disturbing and

**Comment by OvO7000** [comment]
Can you provide following information?If I can reproduce the error with your information, it will help me location the problem.
- the error text
- the artist and folder you were downloading
- the setting of the extension,you can click the gear icon to go to the setting panel 
- maybe some of the lost image?

**Comment by CashOver** [comment]
Yes I downloaded any album, to have shows as an example:

0. username: alexhuggs
author: R-MK
folderType: collection
folderName: Pokemon
deviation: ~Milotic Chubs~
deviationId: 706341601
error: download failed: error occurred when downloading the file via browser
---------------------------------------
1. username: alexhuggs
author: R-MK
folderType: collection
folderName: Pokemon
deviation: ~The Midnight Moon~
deviationId: 709556720
error: download failed: error occurred when downloading the file via browser
---------------------------------------
2. username: alexhuggs
author: R-MK
folderType: collection
folderName: Pokemon
deviation: ~Egyptian Lucario~
deviationId: 745523305
error: download failed: error occurred when downloading the file via browser
---------------------------------------
3. username: alexhuggs
author: R-MK
folderType: collection
folderName: Pokemon
deviation: ~A Nice Rest~
deviationId: 742839169
error: download failed: error occurred when downloading the file via browser
---------------------------------------
4. username: alexhuggs
author: R-MK
folderType: collection
folderName: Pokemon
deviation: ~Sassy Sneasel~
deviationId: 744332689
error: download failed: error occurred when downloading the file via browser
---------------------------------------
5. username: alexhuggs
author: R-MK
folderType: collection
folderName: Pokemon
deviation: ~Goodra's Pleasure Time~Censored~
deviationId: 715070714
error: download failed: error occurred when downloading the file via browser
---------------------------------------
6. username: alexhuggs
author: R-MK
folderType: collection
folderName: Pokemon
deviation: ~Lucario Dealer~
deviationId: 705462499
error: download failed: error occurred when downloading the file via browser
---------------------------------------
7. username: alexhuggs
author: R-MK
folderType: collection
folderName: Pokemon
deviation: ~Delphox's Pleasure Time~Cropped~
deviationId: 673658024
error: download failed: error occurred when downloading the file via browser
---------------------------------------
8. username: alexhuggs
author: pitch-black-crow
folderType: collection
folderName: Pokemon
deviation: .:Struggle:.
deviationId: 624979393
error: download failed: error occurred when downloading the file via browser
---------------------------------------
9. username: alexhuggs
author: R-MK
folderType: collection
folderName: Pokemon
deviation: ~Glaceon+Sylveon Cheers~
deviationId: 673116459
error: download failed: error occurred when downloading the file via browser
---------------------------------------
10. username: alexhuggs
author: pitch-black-crow
folderType: collection
folderName: Pokemon
deviation: .:Afraid_eats_Hyperberry:.
deviationId: 620736752
error: download failed: error occurred when downloading the file via browser
---------------------------------------
11. username: alexhuggs
author: R-MK
folderType: collection
folderName: Pokemon
deviation: ~April and May~
deviationId: 666886616
error: download failed: error occurred when downloading the file via browser
---------------------------------------
12. username: alexhuggs
author: R-MK
folderType: collection
folderName: Pokemon
deviation: ~Grass Snake Jugs~
deviationId: 665494557
error: download failed: error occurred when downloading the file via browser
---------------------------------------
13. username: alexhuggs
author: R-MK
folderType: collection
folderName: Pokemon
deviation: ~Charizard Chub~
deviationId: 656797025
error: download failed: error occurred when downloading the file via browser
---------------------------------------
14. username: alexhuggs
author: R-MK
folderType: collection
folderName: Pokemon
deviation: ~Xmas 2016 : Festive Booty~
deviationId: 653126081
error: download failed: error occurred when downloading the file via browser
---------------------------------------
15. username: alexhuggs
author: pitch-black-crow
folderType: collection
folderName: Pokemon
deviation: .:Mikaku_eats_Hyperberry:.
deviationId: 620736772
error: download failed: error occurred when downloading the file via browser
---------------------------------------
16. username: alexhuggs
author: R-MK
folderType: collection
folderName: Pokemon
deviation: ~Salazzle Bubble Booty~
deviationId: 650688000
error: download failed: error occurred when downloading the file via browser
---------------------------------------
17. username: alexhuggs
author: R-MK
folderType: collection
folderName: Pokemon
deviation: ~Primarina Babe~
deviationId: 644330521
error: download failed: error occurred when downloading the file via browser
---------------------------------------
18. username: alexhuggs
author: R-MK
folderType: collection
folderName: Pokemon
deviation: ~Primarina Babe~No Skirt~
deviationId: 644332642
error: download failed: error occurred when downloading the file via browser
---------------------------------------
19. username: alexhuggs
author: R-MK
folderType: collection
folderName: Pokemon
deviation: ~Giratina Babe~
deviationId: 641566228
error: download failed: error occurred when downloading the file via browser
---------------------------------------
20. username: alexhuggs
author: R-MK
folderType: collection
folderName: Pokemon
deviation: ~Wet Zoroark~
deviationId: 633297351
error: download failed: error occurred when downloading the file via browser
---------------------------------------
21. username: alexhuggs
author: R-MK
folderType: collection
folderName: Pokemon
deviation: ~Marowak Bebe~
deviationId: 631907405
error: download failed: error occurred when downloading the file via browser
---------------------------------------
22. username: alexhuggs
author: R-MK
folderType: collection
folderName: Pokemon
deviation: ~Marowak Bebe~Sin Pintar
deviationId: 631908830
error: download failed: error occurred when downloading the file via browser
---------------------------------------
23. username: alexhuggs
author: R-MK
folderType: collection
folderName: Pokemon
deviation: ~Mewtwo Bae Doodly~
deviationId: 626449088
error: download failed: error occurred when downloading the file via browser
---------------------------------------
24. username: alexhuggs
author: R-MK
folderType: collection
folderName: Pokemon
deviation: ~Naomi as D.Va~
deviationId: 627975804
error: download failed: error occurred when downloading the file via browser
---------------------------------------
25. username: alexhuggs
author: R-MK
folderType: collection
folderName: Pokemon
deviation: ~Delphox's Service~
deviationId: 609389526
error: download failed: error occurred when downloading the file via browser
---------------------------------------
26. username: alexhuggs
author: R-MK
folderType: collection
folderName: Pokemon
deviation: ~Zorua Dominatrix~
deviationId: 619482997
error: download failed: error occurred when downloading the file via browser
---------------------------------------
27. username: alexhuggs
author: R-MK
folderType: collection
folderName: Pokemon
deviation: ~Reshiram Nerd~
deviationId: 600776852
error: download failed: error occurred when downloading the file via browser
---------------------------------------
28. username: alexhuggs
author: Nirriti72
folderType: collection
folderName: Pokemon
deviation: Scanty pin-up~!
deviationId: 419392799
error: download failed: error occurred when downloading the file via browser
---------------------------------------
29. username: alexhuggs
author: DoodleWill
folderType: collection
folderName: Pokemon
deviation: .: Water Absorb :.
deviationId: 548216435
error: download failed: error occurred when downloading the file via browser
---------------------------------------
30. username: alexhuggs
author: Ullamaliztli
folderType: collection
folderName: Pokemon
deviation: Flame Vixen (CLOSED + FULL PACK AVAILABLE)
deviationId: 452771800
error: TypeError: Failed to construct 'URL': Invalid URL
---------------------------------------
31. username: alexhuggs
author: Rinayru
folderType: collection
folderName: Pokemon
deviation: :::Braixen~Desu:::
deviationId: 413089869
error: download failed: error occurred when downloading the file via browser
---------------------------------------

**Comment by OvO7000** [comment]
- Some of the errors are because of  the exist of : in filename. You can fix this by enable the 'auto rename if has error in filename' in the setting panel.
- Most of the errors are because of the exist of ~ in filename. l have fix this problem in v1.0.2 of the extension, the 
review of the chrome web store will cost several days, youcan try again later, also need to enable the 'auto rename if has error in filename' in the setting panel.
-  The error of deviation Flame Vixen is because that it provides two download methods, and the extension can't get the right download link. If l find some way to solve this, l will publish another version. But since this situation is relatively rare, you can try to manually download these deviations first.

**Comment by CashOver** [comment]
Thank
